In [15]:
import pandas
data = pandas.read_csv("datasets/recipe.csv")
data

    Flour  Milk  Sugar  Butter  Egg  Baking Powder  Vanilla  Salt     Type
0      55    28      3       7    5              2        0     0   Muffin
1      47    24     12       6    9              1        0     0   Muffin
2      47    23     18       6    4              1        0     0   Muffin
3      45    11     17      17    8              1        0     0   Muffin
4      50    25     12       6    5              2        1     0   Muffin
5      55    27      3       7    5              2        1     0   Muffin
6      54    27      7       5    5              2        0     0   Muffin
7      47    26     10      10    4              1        0     0   Muffin
8      50    17     17       8    6              1        0     0   Muffin
9      50    17     17      11    4              1        0     0   Muffin
10     39     0     26      19   14              1        1     0  Cupcake
11     42    21     16      10    8              3        0     0  Cupcake
12     34    17     20      20    5              2        1     0  Cupcake
13     39    13     17      19   10              1        1     0  Cupcake
14     38    15     23      15    8              0        1     0  Cupcake
15     42    18     25       9    5              1        0     0  Cupcake
16     36    14     21      14   11              2        1     0  Cupcake
17     38    15     31       8    6              1        1     0  Cupcake
18     36    16     24      12    9              1        1     0  Cupcake
19     34    17     23      11   13              0        1     0  Cupcake
20     29     3     46       6    0             11        0     6    Scone
21     19     3     36       3   14              7       14     5    Scone
22     20     5     52       5   10              3        0     5    Scone
23     19     6     50       5    6             10        0     3    Scone
24     19    10     51       5    0             10        0     5    Scone
25     55    28      3       7    5              2        0     0   Muffin
26     47    24     12       6    9              1        0     0   Muffin
27     47    23     18       6    4              1        0     0   Muffin
28     45    11     17      17    8              1        0     0   Muffin
29     50    25     12       6    5              2        1     0   Muffin
30     55    27      3       7    5              2        1     0   Muffin
31     54    27      7       5    5              2        0     0   Muffin
32     48    26     10      10    4              1        0     0   Muffin
33     50    17     17       8    6              1        0     0   Muffin
34     50    17     17      11    4              1        0     0   Muffin
35     38     0     26      19   14              1        1     0  Cupcake
36     42    21     16      10    8              3        0     0  Cupcake
37     34    17     20      20    5              2        1     0  Cupcake
38     39    13     17      18   10              1        1     0  Cupcake
39     38    15     23      15    8              0        1     0  Cupcake
40     41    18     25       9    5              1        0     0  Cupcake
41     36    14     21      14   11              2        1     0  Cupcake
42     38    15     31       8    6              1        1     0  Cupcake
43     36    16     24      12    9              1        1     0  Cupcake
44     34    17     23      11   12              0        1     0  Cupcake
45     29     3     46       6    0             11        0     6    Scone
46     19     3     36       3   14              7       14     5    Scone
47     20     5     52       5   10              3        0     5    Scone
48     19     6     50       5    6             10        0     3    Scone
49     19    10     51       5    0             10        0     5    Scone

In [16]:
data.describe()

,Flour,Milk,Sugar,Butter,Egg,Baking Powder,Vanilla,Salt
count,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000
mean,39.340000,15.920000,23.080000,9.740000,6.940000,2.680000,0.960000,0.960000
std,11.213348,8.090912,14.037617,4.898188,3.644453,3.152194,2.732719,1.989359
min,19.000000,0.000000,3.000000,3.000000,0.000000,0.000000,0.000000,0.000000
25%,34.000000,11.000000,16.000000,6.000000,5.000000,1.000000,0.000000,0.000000
50%,39.000000,17.000000,20.000000,8.000000,6.000000,1.000000,0.000000,0.000000
75%,47.750000,23.000000,26.000000,12.000000,9.000000,2.000000,1.000000,0.000000
max,55.000000,28.000000,52.000000,20.000000,14.000000,11.000000,14.000000,6.000000

In [17]:
# separate the ingredients from the outcome
array = data.values
#X shall represent the training data => inputs/features/labels
# Y shall represent the outcome => prediction
X = array[:, 0:10]

Y= array[:,8]

In [ ]:
# split the data even further 

from sklearn import model_selection

X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y, test_size=0.3, random_state=42)

In [4]:
from sklearn.svm import SVC

In [5]:
model = SVC()

In [1]:
model.fit(X_train,Y_train)

NameError: name 'model' is not defined

In [ ]:
# test the model to see what it will predict
predictions = model.predict(X_test)

print("Model predicted: ", predictions)
print("We expected: ", Y_test)

NotFittedError: This SVC instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [ ]:
# Test the accuracy score of the model
from sklearn.metrics import accuracy_score
print("Accuracy: ", accuracy_score(Y_test, predictions))

NameError: name 'predictions' is not defined

In [ ]:
recipe =[ [10,7,8,1,4,1,6,3]]
outcome = model.predict(recipe)
print("You will be cooking a ",outcome)

NotFittedError: This SVC instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [ ]:
# Imports Classification Models
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.svm import SVC

# Create an Empty List and append all models, Give the Models an alias Name
# i.e we called KNeighborsClassifier() alias KNC etc
models = []
models.append(('D Trees', DecisionTreeClassifier()))
models.append(('Gaussian', GaussianNB()))
models.append(('KNC', KNeighborsClassifier()))
models.append(('Random Forest', RandomForestClassifier()))
models.append(('Gradient Boosting', GradientBoostingClassifier()))
models.append(('Linear Disc', LinearDiscriminantAnalysis()))
models.append(('Support Machines', SVC(gamma = 'auto')))

# Import Cross Validation and KFOLD
from sklearn.model_selection import cross_val_score, KFold
# Create a for loop so that each model is tested in turn
for name, model in models:
            # Here we do a 10 split K-FOLD - We split our data into 10 Folds
            kfold = KFold(n_splits = 10, random_state=42, shuffle=True)

            # We Train and Test the current model in the Loop
            # Get the results for each Fold
            cv_results = cross_val_score(model, X_train, Y_train, cv = kfold,
            scoring='accuracy')

            # Get the average of all Folds For that specific model in the Loop
            print(name, ' Results:= ', cv_results.mean())

ValueError:
All the 10 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
9 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Pc\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Pc\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\Pc\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\tree\_classes.py", line 1027, in fit
    super()._fit(
    ~~~~~~~~~~~~^
        X,
        ^^
    ...<2 lines>...
        check_input=check_input,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\Pc\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\tree\_classes.py", line 255, in _fit
    X, y = validate_data(
           ~~~~~~~~~~~~~^
        self, X, y, validate_separately=(check_X_params, check_y_params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\Pc\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py", line 2914, in validate_data
    X = check_array(X, input_name="X", **check_X_params)
  File "c:\Users\Pc\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py", line 1022, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
  File "c:\Users\Pc\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\_array_api.py", line 878, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
ValueError: could not convert string to float: 'Muffin'

--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Pc\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Pc\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\Pc\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\tree\_classes.py", line 1027, in fit
    super()._fit(
    ~~~~~~~~~~~~^
        X,
        ^^
    ...<2 lines>...
        check_input=check_input,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\Pc\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\tree\_classes.py", line 255, in _fit
    X, y = validate_data(
           ~~~~~~~~~~~~~^
        self, X, y, validate_separately=(check_X_params, check_y_params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\Pc\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py", line 2914, in validate_data
    X = check_array(X, input_name="X", **check_X_params)
  File "c:\Users\Pc\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py", line 1022, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
  File "c:\Users\Pc\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\_array_api.py", line 878, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
ValueError: could not convert string to float: 'Cupcake'